/**
 * Abstract syntax tree (AST) node definitions for Stmt.
 * <p>
 * Auto-generated by tool/GenerateAst.java. Do NOT edit manually.
 * </p>
 */
package io.github.journeycodesayush.javabhailang.parser;

import io.github.journeycodesayush.javabhailang.lexer.Token;
import java.util.List;

public abstract class Stmt {
  /**
   * Visitor interface for Stmt nodes.
   * Each concrete node implements the accept() method.
   */
  public interface Visitor<R> {
    public R visitBlockStmt(Block stmt);

    public R visitExpressionStmt(Expression stmt);

    public R visitIfStmt(If stmt);

    public R visitPrintStmt(Print stmt);

    public R visitVarStmt(Var stmt);

    public R visitWhileStmt(While stmt);

    public R visitBreakStmt(Break stmt);

    public R visitContinueStmt(Continue stmt);
  }

  public static class Block extends Stmt {
    public Block(List<Stmt> statements) {
      this.statements = statements;
    }

    public final List<Stmt> statements;

    @Override
    public <R> R accept(Visitor<R> visitor) {
      return visitor.visitBlockStmt(this);
    }
  }

  public static class Expression extends Stmt {
    public Expression(Expr expression) {
      this.expression = expression;
    }

    public final Expr expression;

    @Override
    public <R> R accept(Visitor<R> visitor) {
      return visitor.visitExpressionStmt(this);
    }
  }

  public static class If extends Stmt {
    public If(Expr condition, Stmt thenBranch, Stmt elseBranch) {
      this.condition = condition;
      this.thenBranch = thenBranch;
      this.elseBranch = elseBranch;
    }

    public final Expr condition;
    public final Stmt thenBranch;
    public final Stmt elseBranch;

    @Override
    public <R> R accept(Visitor<R> visitor) {
      return visitor.visitIfStmt(this);
    }
  }

  public static class Print extends Stmt {
    public Print(Expr expression) {
      this.expression = expression;
    }

    public final Expr expression;

    @Override
    public <R> R accept(Visitor<R> visitor) {
      return visitor.visitPrintStmt(this);
    }
  }

  public static class Var extends Stmt {
    public Var(Token name, Expr initializer) {
      this.name = name;
      this.initializer = initializer;
    }

    public final Token name;
    public final Expr initializer;

    @Override
    public <R> R accept(Visitor<R> visitor) {
      return visitor.visitVarStmt(this);
    }
  }

  public static class While extends Stmt {
    public While(Expr condition, Stmt body) {
      this.condition = condition;
      this.body = body;
    }

    public final Expr condition;
    public final Stmt body;

    @Override
    public <R> R accept(Visitor<R> visitor) {
      return visitor.visitWhileStmt(this);
    }
  }

  public static class Break extends Stmt {
    public Break() {
    }

    @Override
    public <R> R accept(Visitor<R> visitor) {
      return visitor.visitBreakStmt(this);
    }
  }

  public static class Continue extends Stmt {
    public Continue() {
    }

    @Override
    public <R> R accept(Visitor<R> visitor) {
      return visitor.visitContinueStmt(this);
    }
  }

  public abstract <R> R accept(Visitor<R> visitor);
}
