// Auto-generated by tool/GenerateAst.java. Do NOT edit it manually

package io.github.journeycodesayush.javabhailang.parser;

import io.github.journeycodesayush.javabhailang.lexer.Token;
import java.util.List;

public abstract class Stmt {
  public interface Visitor<R> {
    public R visitBlockStmt(Block stmt);

    public R visitExpressionStmt(Expression stmt);

    public R visitPrintStmt(Print stmt);

    public R visitVarStmt(Var stmt);
  }

  public static class Block extends Stmt {
    public Block(List<Stmt> statements) {
      this.statements = statements;
    }

    public final List<Stmt> statements;

    @Override
    public <R> R accept(Visitor<R> visitor) {
      return visitor.visitBlockStmt(this);
    }
  }

  public static class Expression extends Stmt {
    public Expression(Expr expression) {
      this.expression = expression;
    }

    public final Expr expression;

    @Override
    public <R> R accept(Visitor<R> visitor) {
      return visitor.visitExpressionStmt(this);
    }
  }

  public static class Print extends Stmt {
    public Print(Expr expression) {
      this.expression = expression;
    }

    public final Expr expression;

    @Override
    public <R> R accept(Visitor<R> visitor) {
      return visitor.visitPrintStmt(this);
    }
  }

  public static class Var extends Stmt {
    public Var(Token name, Expr initializer) {
      this.name = name;
      this.initializer = initializer;
    }

    public final Token name;
    public final Expr initializer;

    @Override
    public <R> R accept(Visitor<R> visitor) {
      return visitor.visitVarStmt(this);
    }
  }

  public abstract <R> R accept(Visitor<R> visitor);
}
